<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.tagtraum</groupId>
        <artifactId>ffsampledsp</artifactId>
        <version>0.9.54</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>com.tagtraum</groupId>
    <artifactId>ffsampledsp-java</artifactId>
    <version>0.9.54</version>
    <packaging>jar</packaging>
    <name>FFSampledSP Java Library</name>
    <description>Java implementation of FFSampledSP.</description>

    <licenses>
        <license>
            <name>LGPL 2.1</name>
            <url>https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt</url>
            <comments>LGPL 2.1</comments>
        </license>
    </licenses>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/native</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>